package entanglecraft.generation;

import java.util.Random;

import net.minecraft.world.World;
import entanglecraft.EntangleCraft;
import entanglecraft.blocks.EntangleCraftBlocks;

public class WorldGenLambdaOre {
	private int[] ores = {EntangleCraftBlocks.BlockRedShard.blockID,EntangleCraftBlocks.BlockYelShard.blockID,EntangleCraftBlocks.BlockBluShard.blockID};
    public WorldGenLambdaOre()
    {
    }

    public boolean generate(World world, Random random, int i, int j, int k)
    {
    	if (random.nextInt(20) == 1)
    	{
	    	int blockToGen = WorldGenFunctions.chooseRandomItem(random, ores);
	    	
			int i1 = i;
			int j1 = j;
			int k1 = k;
	
	        i1 = i + random.nextInt(256) * random.nextInt(1) == 0 ? -1 : 1;
	        j1 = j + random.nextInt(16) - random.nextInt(16);
	        k1 = k + random.nextInt(256) * random.nextInt(1) == 0 ? -1 : 1;
		    
	        if (world.getBlockId(i1, j1, k1) != 0 && world.getBlockId(i1, j1, k1)!= EntangleCraftBlocks.BlockFObsidian.blockID)
	        {
	        	System.out.println("created an ore");
	        	world.setBlockWithNotify(i1, j1, k1,blockToGen);
	        	EntangleCraft.dhInstance.oreGenCount += 1;
	        	
	        	if (EntangleCraft.dhInstance.oreGenCount > 0 && EntangleCraft.dhInstance.oreGenCount % 16 == 0)
	        	{
	        		System.out.println(EntangleCraft.dhInstance.oreGenCount + " ores generated by EntangleCraft\n");
	        	}
	    	
	        }
    	
	    }
	    return true;
    }
    
}
